### Case Study 1: Filtering Sensor Reading
#### Problem: 
- A temperature sensor records integer readings every minute in the range of 10 degree celcius to 50 degree celcius. You need to extract only the even temperature reading for further statistical anlysis.
                                                                                                                                                                          
#### Task:
- Using Numpy,create a range of reading from 10 to 50(inclusive) and filter out only the even values.
  - Solution:

In [1]:
import numpy as np
readings = np.arange(10,51)
even_readings = readings[readings%2==0]
print(even_readings)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


### Case Study 2: Matrix Reshaping for Image Processing
#### Problem:
- You're working with an image processing team. A grayscale image is sent to your backend as a 1D array of pixel intensities (values 0-255).You know the images is 3*4 inshape and need to reshape the flat array to a 2D format for processing.

#### Task:
- Use Numpy to reshape a 1D array of 12 values into a 3*4 matrix.
  - Solution:

In [3]:
import numpy as np
pixels = np.arange(12)
image = pixels.reshape(3,4)
print(image)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Case Study 3: Anomaly Detection in IoT Data
#### Problem:
- You're analyzing IoT device logs. Each second, a sensor outputs a number from 0-9. Odd values are considered noisy. You are asked to replace all add values with -1 for easy anomaly tagging.
#### Task:
- Generate an array from 0 to 9 and replace all odd numbers with -1
  - Solution:

In [4]:
import numpy as np
data = np.arange(10)
data[data%2==1] = -1
print(data)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Case Study 4: Vector Operations in Machine Learing
#### Problem:
- In a machine learning project, you need to compute the dot product between two feature vectors for similarity checking:[1,2,3] and [4,5,6].
#### Task:
- Calculate the dot product using Numpy.
  - Solution:

In [6]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
dot_product = np.dot(a,b)
print('dot product:',dot_product)

dot product: 32


### Case Study 5: Data Cleaning with Missing Values
#### Problem:
- A CSV file is loaded into memory, and some numeric values are missing, represented as NaN. You are asked to replace all NaN values with 0 so that downstream process don't fail.
#### Task:
- Replace all NaNs in the array with 0.
  - Solution:

In [8]:
arr = np.array([1,np.nan,2,np.nan,3,np.nan])
arr_cleaned = np.nan_to_num(arr)
print(arr_cleaned)

[1. 0. 2. 0. 3. 0.]


### Case Study 6: Generating Test Image Data
#### Problem:
- Your computer vision team asks you to generate a 5*5 grayscale test matrix with values from 0 to 24 to simulate image pixel intensities.
  - Solution:

In [10]:
import numpy as np
image = np.arange(25)
test_matrix = image.reshape(5,5)
print(test_matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [12]:
import numpy as np
image = np.arange(25).reshape(5,5)
print('A 5*5 matrix with values: \n',image)

A 5*5 matrix with values: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Case Study 7: Indentity Matrix for Linear Algebra
#### Problem:
- While solving linear equations, you're asked to create a 3*3 identity matrix as the base for matrix oprations.
  - Solution: 

In [13]:
import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Case Study 8: Diagonal Feature Extraction
#### Problem:
- You are given a 3*3 matrix to financial weights and are asked to extract the diagonal elements to analyze principal contributions.
  - Solution:

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print()
diagonal_element = np.diag(arr)
print(diagonal_element)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 5 9]


### Case Study 9: Vector Flattening for API Integration
#### Problem:
- An API only accepts 1D arrays. You receive a 2D array. Flatten it make it compatible with the request.
  - Solution:

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print()
flat = arr.flatten()
print(flat)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


### Case Study 10: Column-Wise Statistics for Course Scores
#### Problem:
- You are given a 2D array of score for multiple students across two tests. Calculate the average score per test.
  - Solution:                                                                    

In [17]:
import numpy as np
arr = np.array([[1,2],[3,4]])
print(np.mean(arr,axis=0))

[2. 3.]


In [23]:
arr = np.array([[1,2],[3,4]])
print(arr)
print()
print(np.mean(arr,axis=0))

[[1 2]
 [3 4]]

[2. 3.]


### Case Study 11: Unique Values in Survey Data
#### Problem :
- Your survey response array contains repeated entries. Return unique participant ID's
  - Solution: 

In [2]:
import numpy as np
response = np.array([1,2,2,3,3,3])
print(np.unique(response))

[1 2 3]


### Case Study 12: Clipping Scores to a Threshold
#### Problem:
- You want to cap all scores above 5 to 5 and below 2 to  2 for a skill system.
  - Solution:                                                           

In [1]:
import numpy as np
scores = np.array([1,2,3,4,5,5])
print(np.clip(scores,2,5))

[2 2 3 4 5 5]


### Case Study 13: Stack Time Series Vertically
#### Problem:
- Two 1D time series need to be stacked as row of a matrix for comparison.
  - Solution:

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.hstack((a,b)))

[1 2 3 4 5 6]


### Case Study 14: Stack Single Array Horizontally
#### Problem:
- Combine two data stream as a single concatenated stream.
  - Solution:

In [5]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.hstack((a,b)))

[1 2 3 4 5 6 7 8]


### Case Study 15: Measuring Variability in Feedback Scores
#### Problem:
- Analyze how spread out customer rating are using standard deviation.
  - Solution:

In [6]:
rating = np.array([1,2,3,4,5])
print(np.std(rating))

1.4142135623730951


### Case Study 16: Sorting IDs Before Submission
#### Problem:
- You need to sort participant IDs before uploading them to the database.
  - Solution:

In [7]:
ids = np.array([3,1,2,5,4])
print(np.sort(ids))

[1 2 3 4 5]


### Case Study 17: Counting Events Over Threshold
#### Problem:
- In a log, count how many events had scores>3
  - Solution:

In [8]:
arr = np.array([1,3,4,5])
print(np.sum(arr>3))

2


### Case Study 18: Matrix Multiplication in Recommendation System
#### Problem:
- Multiply two matrices representing user preferences and item features.
  - Solution:

In [9]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[3,4]])
print(np.matmul(a,b))

[[11 14]
 [27 34]]


### Case Study 19: Broadcasting Scores Across Features
#### Problem:
- A 1D array needs to be **added to each row** of a 2D matrix.
  - Solution:

In [10]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])
print(a+b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


### Case Study 20: Generating Random Noise Matrix for Simulation
#### Problem:
- You need to simulate a 3*3 matrix of noise values between 0 to 1.
  - Solution:

In [15]:
noise = np.random.rand(3,3)
print(noise)

[[0.75487948 0.95826144 0.95880242]
 [0.74292231 0.275725   0.03372288]
 [0.68444368 0.11553224 0.57436319]]
